/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobuscaminas;
import java.awt.*;
import java.io.*;
import java.net.Socket;
import javax.swing.*;
/**
 *
 * @author davek
 */
public class Juego extends javax.swing.JPanel {

    private JButton[][] botones;
    private Tablero tableroLogico;
    private Socket socket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    private boolean esMiTurno = false;
    
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelTablero1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(92, 103, 125));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(92, 103, 125));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Buscaminas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(797, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(92, 103, 125));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Posiciones");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("[posiciones]");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(493, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(92, 103, 125));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Salir");
        btnRegresar.setActionCommand("");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tools");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(92, 103, 125));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mi tiempo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("00:00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(1353, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(92, 103, 125));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(92, 103, 125));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel7)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(92, 103, 125));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel8)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.LINE_END);

        panelTablero1.setBackground(new java.awt.Color(255, 255, 255));
        panelTablero1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 6, true));
        panelTablero1.setMaximumSize(new java.awt.Dimension(450, 450));
        panelTablero1.setMinimumSize(new java.awt.Dimension(450, 450));

        javax.swing.GroupLayout panelTablero1Layout = new javax.swing.GroupLayout(panelTablero1);
        panelTablero1.setLayout(panelTablero1Layout);
        panelTablero1Layout.setHorizontalGroup(
            panelTablero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        panelTablero1Layout.setVerticalGroup(
            panelTablero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel5.add(panelTablero1, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void iniciarJuegoConConexion(Socket s, ObjectOutputStream o, ObjectInputStream i) {
        this.socket = s;
        this.out = o;
        this.in = i;
        
        panelTablero1.setVisible(false);

        // Hilo de escucha del Cliente
        new Thread(() -> {
            try {
                while (true) {
                    Mensaje msg = (Mensaje) in.readObject();
                    procesarMensaje(msg);
                }
            } catch (Exception e) {
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, "Conexión perdida con el servidor.");
                    btnRegresar.doClick();
                });
            }
        }).start();
    }

    private void procesarMensaje(Mensaje msg) {
        SwingUtilities.invokeLater(() -> {
            switch (msg.getTipo()) {
                case "INICIO":
                    tableroLogico = (Tablero) msg.getContenido();
                    crearTableroVisual();
                    panelTablero1.setVisible(true);
                    break;
                    
                case "TURNO":
                    esMiTurno = (boolean) msg.getContenido();
                    bloquearBotonesSegunTurno();
                    break;
                    
                case "CASILLA_ACTUALIZADA":
                    String[] datos = ((String) msg.getContenido()).split(",");
                    actualizarCasillaRemota(Integer.parseInt(datos[0]), Integer.parseInt(datos[1]), Integer.parseInt(datos[2]));
                    break;
                    
                case "GANASTE":
                case "PERDISTE":
                    String texto = msg.getTipo().equals("GANASTE") ? "¡VICTORIA!" : "DERROTA :(";
                    int op = JOptionPane.showConfirmDialog(this, texto + "\n" + msg.getContenido() + "\n¿Jugar otra vez?", "Fin de Partida", JOptionPane.YES_NO_OPTION);
                    
                    if (op == JOptionPane.YES_OPTION) {
                        enviarMensaje("BUSCAR_PARTIDA", "Clasico");
                        panelTablero1.setVisible(false);
                    } else {
                        btnRegresar.doClick();
                    }
                    break;
                    
                case "OPONENTE_DESCONECTADO":
                     JOptionPane.showMessageDialog(this, "El oponente se desconectó.");
                     btnRegresar.doClick();
                     break;
            }
        });
    }

    private void crearTableroVisual() {
        panelTablero1.removeAll();
        int f = tableroLogico.getFilas();
        int c = tableroLogico.getColumnas();
        panelTablero1.setLayout(new GridLayout(f, c));
        botones = new JButton[f][c];
        
        // Tamaño fijo para evitar que se vea gigante
        panelTablero1.setPreferredSize(new Dimension(c * 35, f * 35));

        for (int i = 0; i < f; i++) {
            for (int j = 0; j < c; j++) {
                JButton btn = new JButton();
                btn.setMargin(new Insets(0,0,0,0));
                btn.setFont(new Font("Arial", Font.BOLD, 12));
                final int r = i;
                final int col = j;
                btn.addActionListener(e -> clickCasilla(r, col));
                botones[i][j] = btn;
                panelTablero1.add(btn);
            }
        }
        
        panelTablero1.revalidate();
        panelTablero1.repaint();
        
        // Forzar empaquetado
        Window w = SwingUtilities.getWindowAncestor(this);
        if(w instanceof JFrame) ((JFrame)w).pack();
    }

    private void clickCasilla(int f, int c) {
        if (!esMiTurno) return;
        
        Casilla casilla = tableroLogico.getCasilla(f, c);
        if (casilla.esRevelado()) return;

        // Acción local inmediata para feedback visual
        casilla.setRevelado(true);
        botones[f][c].setEnabled(false);
        botones[f][c].setBackground(Color.LIGHT_GRAY);

        if (casilla.isMina()) {
            botones[f][c].setBackground(Color.RED);
            botones[f][c].setText("X");
            enviarMensaje("PERDIO", null);
        } else {
            if(casilla.getVecinos() > 0) {
                botones[f][c].setText("" + casilla.getVecinos());
                colorearNumero(botones[f][c], casilla.getVecinos());
            }
            enviarMensaje("CLICK", f + "," + c);
        }
    }
    
    private void actualizarCasillaRemota(int f, int c, int vecinos) {
        if(f >= 0 && f < botones.length && c >= 0 && c < botones[0].length) {
             botones[f][c].setEnabled(false);
             botones[f][c].setBackground(Color.LIGHT_GRAY);
             if(vecinos > 0) {
                 botones[f][c].setText(String.valueOf(vecinos));
                 colorearNumero(botones[f][c], vecinos);
             }
        }
    }
    
    private void colorearNumero(JButton btn, int n) {
        switch(n) {
            case 1: btn.setForeground(Color.BLUE); break;
            case 2: btn.setForeground(new Color(0, 128, 0)); break; // Verde oscuro
            case 3: btn.setForeground(Color.RED); break;
            default: btn.setForeground(new Color(0, 0, 128)); break;
        }
    }

    private void bloquearBotonesSegunTurno() {
        if (botones == null) return;
        // Solo cambiamos la interactividad global del panel, no botón por botón para no afectar a los revelados
        // Pero Swing JButton enabled es visual.
        // La protección real está en clickCasilla: if (!esMiTurno) return;
    }

    private void enviarMensaje(String tipo, Object contenido) {
        try {
            if (out != null) {
                out.writeObject(new Mensaje(tipo, contenido));
                out.flush();
                out.reset(); // CRÍTICO
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        try { socket.close(); } catch(Exception e){}
        CardLayout cl = (CardLayout) getParent().getLayout();
        cl.show(getParent(), "menu");
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelTablero1;
    // End of variables declaration//GEN-END:variables
}
