/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobuscaminas;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import java.awt.CardLayout; // IMPORTANTE: Importación corregida


/**
 *
 *
 * @author davek
 */
public class Menu extends Fondo {
    private Socket socketTemp;
    private ObjectOutputStream outTemp;
    private ObjectInputStream inTemp;
    /**
     * Creates new form Menu
     */
    public Menu() {
        super("/proyectobuscaminas/imagenes/abstractbg.jpg");
        
        initComponents();
        
        Deco deco = new Deco();
        
        deco.agregarAnimacionHover(btnJugar);
        deco.agregarAnimacionHover(btnLogin);
        deco.agregarAnimacionHover(btnRegistro);
        deco.agregarAnimacionHover(btnRecords);

        
        if (Musica.getInstance().isPlaying()) {
            btnMusic.setText("ON");
        } else {
            btnMusic.setText("OFF");
        }
    }

    private boolean conectarServidor() {
        try {
            if (socketTemp == null || socketTemp.isClosed()) {
                socketTemp = new Socket("localhost", 12345);
                outTemp = new ObjectOutputStream(socketTemp.getOutputStream());
                inTemp = new ObjectInputStream(socketTemp.getInputStream());
            }
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede conectar al servidor.");
            return false;
        }
    }
    
    private void irAlJuego(Socket s, ObjectOutputStream o, ObjectInputStream i) {
        // El componente en el índice 1 del panel padre (Ventana) es Juego.java
        Juego panelJuego = (Juego) getParent().getComponent(1);
        panelJuego.iniciarJuegoConConexion(s, o, i);
        
        // Obtenemos el CardLayout del panel padre (que es mainPanel en Ventana.java)
        java.awt.CardLayout cl = (java.awt.CardLayout) getParent().getLayout();
        cl.show(getParent(), "juego");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMusic = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnRecords = new javax.swing.JButton();

        setBackground(new java.awt.Color(92, 103, 125));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(92, 103, 125));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobuscaminas/imagenes/intentodelogo1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 88, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        btnMusic.setBackground(new java.awt.Color(255, 255, 255));
        btnMusic.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnMusic.setForeground(new java.awt.Color(0, 0, 0));
        btnMusic.setText("ON");
        btnMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 0, 6);
        jPanel1.add(btnMusic, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(92, 103, 125));
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(92, 103, 125));
        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(92, 103, 125));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBackground(new java.awt.Color(92, 103, 125));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        btnJugar.setBackground(new java.awt.Color(255, 255, 255));
        btnJugar.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(0, 0, 0));
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel6.add(btnJugar);
        btnJugar.setBounds(20, 20, 320, 55);

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Iniciar sesion");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel6.add(btnLogin);
        btnLogin.setBounds(20, 110, 320, 58);

        btnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro.setFont(new java.awt.Font("Comic Sans MS", 1, 35)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistro.setText("Registrar usuario");
        btnRegistro.setPreferredSize(new java.awt.Dimension(187, 57));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel6.add(btnRegistro);
        btnRegistro.setBounds(20, 210, 320, 57);

        btnRecords.setBackground(new java.awt.Color(255, 255, 255));
        btnRecords.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        btnRecords.setForeground(new java.awt.Color(0, 0, 0));
        btnRecords.setText("Records");
        btnRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordsActionPerformed(evt);
            }
        });
        jPanel6.add(btnRecords);
        btnRecords.setBounds(20, 300, 320, 58);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 364;
        gridBagConstraints.ipady = 389;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 153, 154, 198);
        jPanel4.add(jPanel6, gridBagConstraints);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        if (socketTemp == null || socketTemp.isClosed()) {
            JOptionPane.showMessageDialog(this, "Debes Iniciar Sesion primero.");
            return;
        }

        try {
            // Enviar solicitud de partida (Modo Único: Clasico)
            outTemp.writeObject(new Mensaje("BUSCAR_PARTIDA", "Clasico"));
            
            // Ir a la pantalla de juego
            irAlJuego(socketTemp, outTemp, inTemp);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (!conectarServidor()) return;

        JTextField nombreField = new JTextField();
        JPasswordField passField = new JPasswordField();
        Object[] inputs = {"Usuario:", nombreField, "Contraseña:", passField};

        int op = JOptionPane.showConfirmDialog(this, inputs, "Login", JOptionPane.OK_CANCEL_OPTION);
        if (op == JOptionPane.OK_OPTION) {
            try {
                String creds = nombreField.getText() + ":" + new String(passField.getPassword());
                outTemp.writeObject(new Mensaje("LOGIN", creds));
                
                Mensaje respuesta = (Mensaje) inTemp.readObject();
                if (respuesta.getTipo().equals("LOGIN_OK")) {
                    JOptionPane.showMessageDialog(this, "Bienvenido " + nombreField.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Error: " + respuesta.getContenido(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) { e.printStackTrace(); }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        if (!conectarServidor()) return;

        JTextField nombreField = new JTextField();
        JPasswordField passField = new JPasswordField();
        Object[] inputs = {"Nuevo Usuario:", nombreField, "Nueva Contraseña:", passField};

        int op = JOptionPane.showConfirmDialog(this, inputs, "Registro", JOptionPane.OK_CANCEL_OPTION);
        if (op == JOptionPane.OK_OPTION) {
            try {
                String creds = nombreField.getText() + ":" + new String(passField.getPassword());
                outTemp.writeObject(new Mensaje("REGISTRO", creds));
                
                Mensaje respuesta = (Mensaje) inTemp.readObject();
                JOptionPane.showMessageDialog(this, respuesta.getContenido());
            } catch (Exception e) { e.printStackTrace(); }
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordsActionPerformed
        if (socketTemp == null || socketTemp.isClosed()) {
            if (!conectarServidor()) {
                JOptionPane.showMessageDialog(this, "Conectate primero.");
                return;
            }
        }
        
        try {
            outTemp.writeObject(new Mensaje("RECORDS", null));
            Mensaje respuesta = (Mensaje) inTemp.readObject();
            
            if (respuesta.getTipo().equals("RECORDS_DATA")) {
                JTextArea textArea = new JTextArea((String) respuesta.getContenido());
                textArea.setEditable(false);
                JScrollPane scrollPane = new JScrollPane(textArea);
                scrollPane.setPreferredSize(new Dimension(400, 300));
                JOptionPane.showMessageDialog(this, scrollPane, "Historial de Partidas", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al obtener records.");
        }
    }//GEN-LAST:event_btnRecordsActionPerformed

    private void btnMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicActionPerformed
        if(Musica.getInstance().isPlaying()){
            Musica.getInstance().stopMusic();
            btnMusic.setText("OFF");
        }else{
            Musica.getInstance().playMusic("recursos/Tobu-Infectious.ogg");
            btnMusic.setText("ON");
        }
    }//GEN-LAST:event_btnMusicActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMusic;
    private javax.swing.JButton btnRecords;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
